title: Public Org-Structure Database
description: Prototype website for a public research database (GitHub Pages)
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
url: "https://HosungKim48.github.io"
baseurl: "/prototypewebsite"
